mysql56:
    restart:       always
    image:         ${MYSQL_IMAGE}
                         # Dockerfile : https://github.com/docker-library/mysql/blob/master/5.6/Dockerfile

    container_name: ${CONTAINER_NAME}

#    build:
#      context: ./
#      dockerfile: Dockerfile

    volumes:
        - ./var/lib/mysql:/var/lib/mysql
        - ./etc/mysql:/etc/mysql
        - ./init.d:/docker-entrypoint-initdb.d


    ports:
#    - HOST:CONTAINER
     - ${VM_PORT}:${DOCKER_PORT}

    environment:
        MYSQL_ROOT_PASSWORD : pass
        MYSQL_DATABASE      : mydb
        MYSQL_USER          : my_user
        MYSQL_PASSWORD      : my_pass

