### SFTP Serter ###
mysftp01:
    image: atmoz/sftp:alpine
    # https://hub.docker.com/r/atmoz/sftp/ 
    # Dockerfile : https://github.com/atmoz/sftp/blob/alpine/Dockerfile

    container_name: mysftp_01

    volumes:
        - ./mysftp:/home/${SFTP_USER}/share
    ports:
        #  HOST:CONTAINER
        - "${SFTP_PORT}:22"

    # command: user        :pass[:e][:uid[:gid]]
    command: ${SFTP_USER}:123:1001


### DB server (mysql) ###
mymysql01:
    restart:       always
    image:         mysql:5.6
    # https://hub.docker.com/_/mysql/
    # Dockerfile : https://github.com/docker-library/mysql/blob/master/5.6/Dockerfile

    container_name: mysql_01

    volumes:
        - ./mymysql01/var/lib/mysql:/var/lib/mysql
        - ./mymysql01/etc/mysql/conf.d:/etc/mysql/conf.d
        - ./mymysql01/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d

    ports:
        #  HOST:CONTAINER
        - 13306:3306

    environment:
        MYSQL_ROOT_PASSWORD : pass
        MYSQL_DATABASE      : mydb
        MYSQL_USER          : my_user
        MYSQL_PASSWORD      : my_pass


### AP server ###
mytomcat01:
    image: tomcat:jre8-alpine
    # https://hub.docker.com/_/tomcat/ 
    # Dockerfile : https://github.com/docker-library/tomcat/blob/master/8.0/jre8-alpine/Dockerfile

    container_name: tomcat_01

    volumes:
        - ./mytomcat01/usr/local/tomcat:/usr/local/tomcat
        - ./mytomcat01/var/log/:/var/log
    ports:
        # HOST:CONTAINER
        - 18080:8080
    links:
        - mysftp01:sftp01
        - mysmtp01:smtp01
        - mymysql01:dbserver01


### Batch server and Build server ###
# Use "docker run"  command !


### FakeSMTP ###
mysmtp01:
    image:         openjdk:8-jdk-alpine
    # https://hub.docker.com/_/java/
    # Dockerfile : https://github.com/docker-library/openjdk/blob/master/8-jdk/alpine/Dockerfile

    container_name: mysmtp_01

    working_dir: /mysmtp
    volumes:
        - ./mysmtp:/mysmtp

    ports:
        #  HOST:CONTAINER
        - 25:2525

    command: java -jar /mysmtp/fakeSMTP-2.0.jar -s -b -p 2525 -a 127.0.0.1 -o .
                       # https://nilhcem.github.io/FakeSMTP/
