FROM python
#FROM python:3.3-alpine
# https://hub.docker.com/_/python/ 

MAINTAINER yangiYA

ENV PYTHONUNBUFFERED 1

EXPOSE 10025


#WORKDIR /smtp/logs

# python -u -m smtpd -c DebuggingServer :8025
ENTRYPOINT ["python3", "-u" , "-m", "smtpd", "-n", "-c", "DebuggingServer", "0.0.0.0::10025"]
